### ISSUE TITLE
Option to pass already existing ForegroundService notification

### ISSUE THREAD

**Issue by Ayman-apps** [IPRoyal/android-pawns-sdk-demo#3]
We need a flag to call the sdk with "ServiceType.FOREGROUND" option but without showing the notification as already our app has a foreground notification and it's not logic to show 2 notifications at the same time.

**Comment by LaurynasM-iproyal** [comment]
Launching foreground service is not possible without showing notification. The only possible solution is to reuse already existing notification. In order to do that, Pawns.startSharing now has secondary method that accepts notification object and its id. That means that consumer now is responsible for correctly managing notifications. Keep in mind these points:

- If you pass Notification to startSharing, then SDK will not create a notification channel, because our service will not create notification itself.
- Notification used in your service and passed to startSharing must have same channel id set to it.
- NotificationId must match the one you pass when launching your own service via startForeground method.

Available in version **1.2.0**
